// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	user "douyin/service/http/internal/handler/user"
	video "douyin/service/http/internal/handler/video"
	"douyin/service/http/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/douyin/relation/action",
				Handler: user.RelationActionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/douyin/relation/follow/list",
				Handler: user.FollowListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/douyin/relation/follower/list",
				Handler: user.FollowerListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/douyin/user",
				Handler: user.GetUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/douyin/user/login",
				Handler: user.LoginUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/douyin/user/register",
				Handler: user.RegisterUserHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/douyin/comment/action",
				Handler: video.CommentActionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/douyin/comment/list",
				Handler: video.CommentListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/douyin/favorite/action",
				Handler: video.FavoriteActionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/douyin/favorite/list",
				Handler: video.FavoriteListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/douyin/feed",
				Handler: video.FeedHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/douyin/publish/action",
				Handler: video.PublishActionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/douyin/publish/list",
				Handler: video.GetPublishListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)
}
